name: Get Spotify Artists Data

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  get-spotify-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install aiohttp playwright pycountry
          python -m playwright install

      - name: Fetch Spotify Artist Data
        run: |
          python src/fetch_artists.py

      - name: Process Artist Data
        run: |
          python src/process_artists.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add public/spotify_artists_data.json
          git add artist_ids.txt
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
