name: Get Artists Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'

jobs:
  get-spotify-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: scripts/requirements.txt

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r scripts/requirements.txt

      - name: Fetch Artists Data
        run: |
          python scripts/fetch_artists.py
          python scripts/world_map.py
          python scripts/ingest_charts.py

        env:
          SP_DC: ${{ secrets.SP_DC }}

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add public/data
          git commit -m "Latest data: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || exit 0
          # rebase to avoid non-fast-forward if another run pushed
          git pull --rebase origin "${GITHUB_REF_NAME:-$GITHUB_REF_NAME}" || true
          git push

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
